accounts/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views
from .views import signup

app_name = 'accounts'

urlpatterns = [
    path('accounts/signup/', signup, name='signup'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/profile/', views.profile_detail, name='profile_detail'),
    path('accounts/profile/edit/',views.profile_edit , name='profile_edit'),
    path('profile/change_password/',views.change_password , name='change_password'),
    path('accounts/activate/<uid>/<token>/', views.activate_email, name='activate_email'),


    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

event/urls.py
from django.urls import path

from event import views

urlpatterns = [
    path('', views.index, name='home'),
    path('event_list/', views.EventList.as_view(), name='event_list'),
    path('<int:pk>/', views.EventDetail.as_view(), name='event_detail'),
]

eventcalender/urls.py
from django.urls import path

from eventcalender import views
from eventcalender.views import EventListView, EventCreateView, EventUpdateView

app_name = 'eventcalender'

urlpatterns = [
    path('', views.home, name='home'),
    path('event_list/', EventListView.as_view(), name='list'),
    path('event_list/<int:event_id>/', views.event_details, name='detail'),
    path('create/', EventCreateView.as_view(), name='create'),
    path('add_member/<int:event_id>', views.add_eventmember, name='add_member'),
    path('update/<int:pk>/', EventUpdateView.as_view(), name='update'),
    # path('delete/<int:pk>/', EventDeleteView.as_view(), name="remove_event"),
    path('event/<int:pk>/remove', views.EventMemberDeleteView.as_view(), name="remove_event"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from project import settings


urlpatterns = [
    path('', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('eventcalender.urls', namespace='eventcalender')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    date = models.DateField()



    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('event:event_detail', args=(self.pk,))

eventcalender/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return '%s' %(self.title)



class EventMember(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['event', 'user']

    def __str__(self):
        return str(self.user)

eventcalender/forms.py
from django import forms
from eventcalender.models import EventMember



class AddMemberForm(forms.ModelForm):
  class Meta:
    model = EventMember
    fields = ['user']

event/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

# Create your views here.
from . models import Event


def index(request):
    return render(request, 'event/index.html')



class EventList(ListView):
    model = Event



class EventDetail(DetailView):
    model = Event

eventcalender/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import request, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from eventcalender.forms import AddMemberForm
from eventcalender.models import Event, EventMember


# home page
def home(request):
    return render(request, 'home/event_list.html')


# page event list view
class EventListView(ListView):
    model = Event
    template_name = 'home/event_list.html'
    context_object_name = 'eventlist'



# create event view
class EventCreateView(LoginRequiredMixin,CreateView):
    fields = ['title', 'description','date', 'time']
    model = Event
    template_name = 'home/event_form.html'
    success_url ="/event_list/"

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(EventCreateView, self).form_valid(form)


# detail view event
@login_required(login_url='accounts:login')
def event_details(request, event_id):
    event = Event.objects.get(id=event_id)
    eventmember = EventMember.objects.filter(event=event)
    context = {
        'event': event,
        'eventmember': eventmember
    }
    return render(request, 'home/event_detail.html', context)





# update event
class EventUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    fields = ("__all__")
    model = Event
    template_name = 'home/event_form.html'
    success_url ="/event_list/"
    fields = ['title', 'description','date','time']

    def test_func(self):
        event = self.get_object()
        if self.request.user == event.user:
            return True
        return False


# create amount of participants
def add_eventmember(request, event_id):
    forms = AddMemberForm()
    if request.method == 'POST':
        forms = AddMemberForm(request.POST)
        if forms.is_valid():
            member = EventMember.objects.filter(event=event_id)
            event = Event.objects.get(id=event_id)
            if member.count() <= 9:
                user = forms.cleaned_data['user']
                EventMember.objects.create(
                    event=event,
                    user=user
                )
                return redirect('eventcalender:list')
            else:
                print('--------------User limit exceed!-----------------')
    context = {
        'form': forms
    }
    return render(request, 'home/add_member.html', context)


# delete event member
class EventMemberDeleteView(generic.DeleteView):
    model = EventMember
    template_name = 'home/confirm_delete.html'
    success_url = reverse_lazy('eventcalender:list')
    context_object_name = 'member'

eventcalender/templates/home/add_member.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap_tags %}
{% block title %}
Add Amount of Participants
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'eventcalender:home' %}"> Home </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form| as_bootstrap }}
    <tr><td colspan="2"><button class="btn btn-success" type="submit"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

eventcalender/templates/home/confirm_delete.html
{% block content%}

<h1>Event Delete?</h1>

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this event?</p>
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'eventcalender:list' %} ">Cancel</a>

</form>
{% endblock content %}

eventcalender/templates/home/event_delete.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

eventcalender/templates/home/event_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>Event Detail</h1><hr/>
<button type="button" class="btn btn-info"><a class="even_link" href="{% url 'eventcalender:home' %}">Home</a></button>
<button type="button" class="btn btn-info"><a class="even_link" href="{% url 'eventcalender:update' event.id %}">Edit Event</a></button>
<button type="button" class="btn btn-info"><a class="even_link" href="{% url 'eventcalender:add_member'  event.id %}">Add Amount of Participants</a></button><hr/>
<div class="container">
    <div class="row">
        <div class="card w-100">
          <div class="card-body">
            <h5 class="card-title">Title: {{ event.title }}</h5>
            <p class="card-text">Date: {{ event.date }}</p>
            <p class="card-text">Description: {{ event.description }}</p>
          </div>
        </div>
    </div>
</div>
<br/><br/>

    <div class="row">
      {% for member in eventmember %}
            <div class="card col-md-4" style="margin-left: 14px;">
              <div class="card-header">
                Amount of Participants: {{ forloop.counter }}
              </div>
              <div class="card-body">
                <h5 class="card-title">User Name: {{ member.user.username }}</h5>
                <p class="card-text">Email: {{ member.user.email }}</p>
                <a href="{% url 'eventcalender:remove_event' member.id %}" class="btn btn-primary">Remove Member</a>
              </div>
            </div>
       {% endfor %}
    </div>



{% endblock %}

eventcalender/templates/home/event_form.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap_tags %}

{% block content%}

<h1>
{% if not form.instance.pk %}
    Create Event
{% else %}
    Update Event
{% endif %}
</h1>
<div class="container">
<form  method="POST" >

    {% csrf_token %}
    {{ form | as_bootstrap }}
    <input type="submit" class='btn btn-primary' value="Submit">

</form>
</div>

{% endblock content %}

eventcalender/templates/home/event_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
 <button type="button" class="btn btn-dark"><a class="even_link" href="{% url 'eventcalender:list' %}">Event List</a></button>
  <button type="button" class="btn btn-dark"><a class="even_link" href="{% url 'eventcalender:create' %}">Create Event</a></button><br/><hr/>

<h1>Event List</h1><br/><hr/>
<div class="container">
    <div class="row">
        {% for event in eventlist %}
        <div class="card" style="width: 18rem;margin-right: 20px;margin-bottom: 14px;">
          <div class="card-body">
            <h5 class="card-title">{{ event.title }}</h5>
            <p class="card-text">Details of event and subscribers.</p>
            <a href="{% url 'eventcalender:detail' event.id %}" class="card-link">Detail Event</a>
          </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

eventcalender/templates/home/index.html
{% extends "base.html" %}
{% load static %}
<h2>Calender Event</h2>
       {% if request.user.is_authenticated %}
        <a href="{% url 'accounts:profile_detail' %}">
         welcome, {{ request.user.username }}
        </a>  <br/>
          <a href="{% url 'accounts:logout' %}">Logout</a><br/><br/>

        {% else %}
          <a href="{% url 'accounts:login' %}">Login</a><br/>
          <a href="{% url 'accounts:signup' %}">Register</a><br/>
        {% endif %}

 {% block content %}
    <button type="button" class="btn btn-dark"><a class="even_link" href="{% url 'eventcalender:list' %}">Event List</a></button>
    <button type="button" class="btn btn-dark"><a class="even_link" href="{% url 'eventcalender:create' %}">Create Event</a></button><br/><hr/>

{% endblock %}