accounts/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views
from .views import signup

app_name = 'accounts'

urlpatterns = [
    path('accounts/signup/', signup, name='signup'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/profile/', views.profile_detail, name='profile_detail'),
    path('accounts/profile/edit/',views.profile_edit , name='profile_edit'),
    path('profile/change_password/',views.change_password , name='change_password'),
    path('accounts/activate/<uid>/<token>/', views.activate_email, name='activate_email'),


    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

event/urls.py
from django.urls import path

from event import views

urlpatterns = [
    path('', views.index, name='home'),
    path('event_list/', views.EventList.as_view(), name='event_list'),
    path('<int:pk>/', views.EventDetail.as_view(), name='event_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from project import settings


urlpatterns = [
    path('', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('eventcalender.urls', namespace='eventcalender')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Questrial|Domine" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <title>{% block head_title %}Event{% endblock %}</title>
</head>

<body>
    <div class="wrapper">
        <!--HEADER-->
        <header>
            <h1 id="logo">
                <a href="{% url 'eventcalender:home' %}">Event</a>
            </h1>
           <div id="controls">
                {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:profile_detail' %}">welcome, {{ request.user.username }}</a>
                <input type="button" id="logout" onclick="location.href='{% url 'accounts:logout' %}'" value="Log out" />
                {% else  %}
                <input type="button" id="login" onclick="location.href='{% url 'accounts:login' %}'" value="Log in" />
                <input type="button" id="signup" onclick="location.href='{% url 'accounts:signup' %}'" value="Register" />
                {% endif %}
            </div>

        </header>

        <!--MAIN-->
        <main>
            {% block content %}{% endblock %}
        </main>
    </div>

    <!--FOOTER-->
    <footer>
        <a href="#" id="scroll-up">
            <i class="fas fa-chevron-up"></i>
        </a>
        <!--2-->
        <p>&copy; 2020 STORE All Rights Reserved.</p>
        <!--2-->
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</body>

</html>